### ISSUE TITLE
List of references missing

### ISSUE THREAD

**Issue by MargotK25** [COMPUTE-Jupyter-course/project-for-compute-jupyter-2022-matonoli#5]
A short citation is given for each image, but they are not mentioned in a reference list making it impossible to find the exact source of the images.

**Suggested solution:**
- [x] Add a list of references

**Comment by matonoli** [comment]
I added the list of references for scientific diagrams taken from publications. For stock photos of the LHC taken from Google, in a notebook like this, I think it's sufficient to just credit and not cite.
